Update "Report a problem with a translation" page
torproject/community pull request #100
Opened 2021-03-01 18:50 UTC by kulsoomzahra

Addressing the issue: https://gitlab.torproject.org/tpo/web/community/-/issues/158

2021-04-09 17:34 UTC, gusgustavo commented on content/localization/translation-problem/contents.lr
> +  Before opening a ticket, see the currently [open tickets for Translations](https://gitlab.torproject.org/groups/tpo/-/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name%5B%5D=Community) becaus
The ticket link is wrong. To see all open tickets: 
https://gitlab.torproject.org/groups/tpo/-/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=Localization 
and 
https://gitlab.torproject.org/tpo/community/l10n/-/issues

2021-04-09 17:35 UTC, gusgustavo requested changes
Please read my comment, then git squash your commits and I will review.

2021-04-09 18:07 UTC, kulsoomzahra commented
Sure, let me know if any other changes are to be made. Thanks

2021-04-12 20:05 UTC, gusgustavo commented
@emmapeel2 can you review this PR? Thanks!

2021-05-19 12:55 UTC, emmapeel2 commented
Apologies, I fixed the issue the other day, without realising there was a pull request. 

This pull request can be closed.

Thanks!

2021-05-19 12:59 UTC, closed without merging