Relay guide for Windows
torproject/community pull request #121
Opened 2021-04-07 17:40 UTC by SehrishHussain

Added relay guide for Windows

@gusgustavo please review.

2021-04-07 22:33 UTC, gusgustavo requested changes
Hi Sehrish, good work! Please check my comments. 

And two more things:

- Some paragraphs are too long and we need to make easier for translators. If you check the example file (https://www.schneier.com/blog/archives/2021/04/wtf-signal-adds-cryptocurrency-support.html), you will see some line breaks after long phrases. Please add that.
2. Have you tried the instructions on your machine? Did it work? While updating docs, it's important to test our own documentation.

2021-04-07 22:33 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +DataDirectory C:Users\torrelay\tor\Data
Missing a `\` here, e.g., `C:\`

2021-04-07 22:33 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +Log notice file C:Users\torrelay\tor\log\notices.log
Missing a `\` here, e.g., `C:\`

2021-04-07 22:33 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +GeoIPFile C:Users\torrelay\tor\Data\Tor\geoip
Missing a `\` here, e.g., `C:\`

2021-04-07 22:33 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +GeoIPv6File C:Users\torrelay\tor\Data\Tor\geoip6
Missing a `\` here, e.g., `C:\`

2021-04-07 22:33 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +```#Change the nickname "myNiceRelay" to a name that you like
You need to break the line here before `#Change` because it's breaking your markdown formatting.

2021-04-07 22:33 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +1. Open your command prompt. Navigate to `C:Users\user\torrelay\tor\Tor` with the command `cd C:Users\user\torrelay\tor\Tor`.
Missing two `\` here, e.g., `C:\`

2021-04-08 08:23 UTC, SehrishHussain commented
@gusgustavo please review the changes. Also I have checked both methods via User Interface and Command line. The instructions are correct. :)

2021-04-08 20:41 UTC, gusgustavo requested changes
Please remove the trailing spaces. And squash your commits, then I will merge. Thanks for working on this!

2021-04-08 20:41 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +
Remove these two trailing spaces. Line 8 and 9.

2021-04-08 20:41 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +
Remove line 14 -  trailing space.

2021-04-08 20:41 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +
Remove line 44, trailing space.

2021-04-08 20:41 UTC, gusgustavo commented on content/relay-operations/technical-setup/guard/windows/contents.lr
> +
Remove line 63, trailing space.

2021-04-09 06:46 UTC, SehrishHussain commented
@gusgustavo I have made 3 commits since the beginning. Shouldn't I squash all three into one?

2021-04-09 06:47 UTC, SehrishHussain commented
@gusgustavo I have made 3 commits since the beginning. Shouldn't I squash all three into one?

2021-04-09 07:18 UTC, SehrishHussain commented
@gusgustavo I have squashed all the commits I made since beginning into one and force pulled the commit. Please review. Thank you for your patience with my learning.

2021-04-09 14:59 UTC, gusgustavo commented
I cherry-picked this commit: https://github.com/torproject/community/pull/121/commits/98173a52bb37742f60adb48e76800bcc476647b9

Tip: name your branch with something more meaningful than "patch", for example, `add-windows-relay-instructions`. It will help you to keep your local git more organized.

2021-04-09 14:59 UTC, closed without merging