More user friendly output of IP addresses
torproject/community pull request #142
Opened 2021-06-29 11:06 UTC by slrslr

In my case it outputs three IPv6 and it does not work, i had to remove /xx suffix from the address - which is not friendly to beginer users. I have not tried if ORPort 9001 works if this port is used by IPv4 already, personally i used "auto" instead of "9001"

If anyone knows better command to output main IPv6 in correct format, please modify it,
i only know
1) i can get main interface name
`$(ip -o -4 route show to default|head -n1|awk '{print $5}')`
but does not know how to get IPs of this interface, not IPs of all interfaces.
2) grep inet6 -A 1 /etc/network/interfaces|grep address
`  address a:b:c:d:1`
(not sure how universal is this command, if to mention it in the tutorial)

2021-09-01 17:50 UTC, anarcat commented on content/relay/setup/post-install/contents.lr
> +ip addr|grep inet6|grep global;echo "Remove /xx suffix from the address"
how about this instead, which would actually remove the /xx suffix and the `inet6` prefix?

```suggestion
ip -6 addr | grep global | sed 's/inet6//;s#/.*##'
```

2021-09-01 17:51 UTC, anarcat requested changes
i think there is a better way, see above comment :)

2021-09-02 11:24 UTC, slrslr commented on content/relay/setup/post-install/contents.lr
> +ip addr|grep inet6|grep global;echo "Remove /xx suffix from the address"
ip -6 addr | grep global | sed 's/inet6//;s#/.*##'
yes, seems to be working in my case to output IPv6 in format ****:****:****:****::1

2021-09-04 17:09 UTC, gusgustavo approved these changes

2021-09-04 17:10 UTC, gusgustavo commented
Cherry-picked into master. Thank you @slrslr and @anarcat!

2021-09-04 17:10 UTC, closed without merging